use serde::Serialize;

use crate::{
    CODED_OPERATOR_CONTRACT_VERSION, COVEQL_AI_PROFILE_VERSION, COVEQL_BRIDGE_CONTRACT_VERSION,
    COVEQL_CORE_VERSION, COVEQL_GRAMMAR_VERSION, COVEQL_GRAPH_PROFILE_VERSION,
    COVEQL_LANGUAGE_VERSION, COVEQL_OBJECT_PROFILE_VERSION, COVEQL_PROFILE_CONTRACT_VERSION,
    COVEQL_TABLE_PROFILE_VERSION, DATAFUSION_COVEQL_REPORT_VERSION, EXPLAIN_JSON_SCHEMA_VERSION,
    LOGICAL_PLAN_VERSION, PHYSICAL_OPERATOR_CONTRACT_VERSION, PHYSICAL_PLAN_VERSION,
    PHYSICAL_SIDECAR_VALIDATION_VERSION, PREDICATE_NORMAL_FORM_VERSION,
    PREDICATE_REPRESENTATION_CONTRACT_VERSION, PROJECTION_DEPENDENCY_CONTRACT_VERSION,
    RESOLVED_AST_VERSION,
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct CoveQlConformanceProfile {
    pub language_version: &'static str,
    pub core_version: &'static str,
    pub grammar_version: &'static str,
    pub resolved_ast_version: &'static str,
    pub logical_plan_version: &'static str,
    pub physical_plan_version: &'static str,
    pub explain_json_schema_version: &'static str,
    pub profile_contract_version: &'static str,
    pub bridge_contract_version: &'static str,
    pub object_profile_version: &'static str,
    pub table_profile_version: &'static str,
    pub graph_profile_version: &'static str,
    pub ai_profile_version: &'static str,
    pub projection_dependency_contract_version: &'static str,
    pub predicate_normal_form_version: &'static str,
    pub coded_operator_contract_version: &'static str,
    pub predicate_representation_contract_version: &'static str,
    pub physical_operator_contract_version: &'static str,
    pub physical_sidecar_validation_version: &'static str,
    pub datafusion_coveql_report_version: &'static str,
    pub mandatory_history_modes: &'static [&'static str],
    pub mandatory_change_modes: &'static [&'static str],
    pub mandatory_functions: &'static [&'static str],
    pub projection_default_order: &'static [&'static str],
    pub evidence_shorthands: &'static [&'static str],
    pub required_fingerprint_fields: &'static [&'static str],
    pub required_coded_explain_fields: &'static [&'static str],
    pub required_coded_operator_contract_fields: &'static [&'static str],
    pub required_physical_sidecar_validation_fields: &'static [&'static str],
    pub required_physical_plan_sidecar_fields: &'static [&'static str],
    pub required_datafusion_scan_negotiation_fields: &'static [&'static str],
    pub required_diagnostic_fields: &'static [&'static str],
    pub required_diagnostic_codes: &'static [&'static str],
    pub conformance_tiers: &'static [CoveQlConformanceTier],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct CoveQlConformanceTier {
    pub tier: u8,
    pub name: &'static str,
    pub authority: &'static str,
    pub required_surfaces: &'static [&'static str],
    pub required_invariant: &'static str,
}

pub const COVEQL_CONFORMANCE_PROFILE: CoveQlConformanceProfile = CoveQlConformanceProfile {
    language_version: COVEQL_LANGUAGE_VERSION,
    core_version: COVEQL_CORE_VERSION,
    grammar_version: COVEQL_GRAMMAR_VERSION,
    resolved_ast_version: RESOLVED_AST_VERSION,
    logical_plan_version: LOGICAL_PLAN_VERSION,
    physical_plan_version: PHYSICAL_PLAN_VERSION,
    explain_json_schema_version: EXPLAIN_JSON_SCHEMA_VERSION,
    profile_contract_version: COVEQL_PROFILE_CONTRACT_VERSION,
    bridge_contract_version: COVEQL_BRIDGE_CONTRACT_VERSION,
    object_profile_version: COVEQL_OBJECT_PROFILE_VERSION,
    table_profile_version: COVEQL_TABLE_PROFILE_VERSION,
    graph_profile_version: COVEQL_GRAPH_PROFILE_VERSION,
    ai_profile_version: COVEQL_AI_PROFILE_VERSION,
    projection_dependency_contract_version: PROJECTION_DEPENDENCY_CONTRACT_VERSION,
    predicate_normal_form_version: PREDICATE_NORMAL_FORM_VERSION,
    coded_operator_contract_version: CODED_OPERATOR_CONTRACT_VERSION,
    predicate_representation_contract_version: PREDICATE_REPRESENTATION_CONTRACT_VERSION,
    physical_operator_contract_version: PHYSICAL_OPERATOR_CONTRACT_VERSION,
    physical_sidecar_validation_version: PHYSICAL_SIDECAR_VALIDATION_VERSION,
    datafusion_coveql_report_version: DATAFUSION_COVEQL_REPORT_VERSION,
    mandatory_history_modes: &["records", "states", "records_and_states"],
    mandatory_change_modes: &[
        "records",
        "state_transitions",
        "property_diffs",
        "final_rows",
    ],
    mandatory_functions: &[
        "isNull",
        "isNotNull",
        "coalesce",
        "cast",
        "lower",
        "upper",
        "trim",
        "length",
        "startsWith",
        "identity",
    ],
    projection_default_order: &[
        "declared_projection_ordering",
        "canonical_row_identity",
        "manifest_or_file_ordinal_then_source_row_ordinal",
    ],
    evidence_shorthands: &[
        "evidence()",
        "evidence(self)",
        "evidence(path)",
        "evidence(root as binding)",
        "evidence(association(...))",
        "evidence(projection(...))",
    ],
    required_fingerprint_fields: &[
        "query_text",
        "parsed_ast",
        "resolved_query",
        "predicate_ast",
        "predicate_cnf",
        "projection_dependency",
        "logical_plan",
        "physical_plan",
    ],
    required_coded_explain_fields: &[
        "eligible",
        "coded_suitability",
        "stage",
        "fallback_reason",
        "fallback_reasons",
        "residual_verification",
        "residual_verification_required",
        "pushed_filters",
        "pushed_columns",
        "operator_contracts",
        "decode_boundaries",
        "bridge_decisions",
        "kernel_shape",
    ],
    required_coded_operator_contract_fields: &[
        "contract_version",
        "operator",
        "representation_class",
        "exact",
        "residual_required",
        "reason",
        "row_grain",
        "proof_obligation",
        "required_metadata",
        "residual_reason",
        "fallback_boundary",
    ],
    required_physical_sidecar_validation_fields: &[
        "report_version",
        "name",
        "status",
        "candidate_count",
        "safe_details",
        "fallback_reason",
        "redacted",
    ],
    required_physical_plan_sidecar_fields: &[
        "proof_validation_report",
        "index_capability_report",
        "layout_range_plan",
        "runtime_compatibility",
        "cache_compatibility",
        "codec_compatibility",
        "zero_copy_eligibility",
        "sidecar_validations",
    ],
    required_datafusion_scan_negotiation_fields: &[
        "report_version",
        "provider_kind",
        "root_kind",
        "dataset_file_count",
        "received_projection_columns",
        "projection_pushdown_supported",
        "projection_pushed_to_coveql",
        "pushed_projection_columns",
        "received_filters",
        "filter_outcomes",
        "pushed_filters",
        "trusted_filters",
        "residual_filters",
        "rejected_filters",
        "lowered_coveql_predicates",
        "proof_states",
        "filters_trusted_exact",
        "received_limit",
        "limit_pushed_to_coveql",
        "pushed_limit",
        "residual_filter_authority",
        "scan_execution_policy",
        "unhandled_residuals",
    ],
    required_diagnostic_fields: &[
        "code",
        "severity",
        "message",
        "span",
        "phase",
        "safe_details",
        "redacted",
    ],
    required_diagnostic_codes: &[
        "E_PARSE",
        "E_UNSUPPORTED_CONSTRUCT",
        "E_DUPLICATE_METHOD",
        "E_METHOD_CONFLICT",
        "E_AMBIGUOUS_PATH",
        "E_UNKNOWN_OBJECT_TYPE",
        "E_UNKNOWN_PROPERTY",
        "E_UNKNOWN_PROJECTION",
        "E_UNKNOWN_EVIDENCE_GRAIN",
        "E_AMBIGUOUS_BRANCH",
        "E_UNSUPPORTED_TEMPORAL_ROLE",
        "E_UNSUPPORTED_HISTORY_MODE",
        "E_UNSUPPORTED_CHANGE_MODE",
        "E_UNSAFE_CODE_DOMAIN",
        "E_STALE_SIDECAR",
        "E_CORRUPT_PROOF",
        "E_RESOURCE_BUDGET_EXCEEDED",
        "E_SECURITY_DISCLOSURE_FORBIDDEN",
        "E_AGGREGATE_DISCLOSURE_FORBIDDEN",
        "E_INDEX_ONLY_FORBIDDEN",
        "E_ZERO_COPY_FORBIDDEN",
        "E_DATAFUSION_PUSH_FILTER_UNSAFE",
        "E_UNSUPPORTED_PROFILE",
        "E_UNSUPPORTED_PROFILE_METHOD",
        "E_UNKNOWN_TABLE_SURFACE",
        "E_UNKNOWN_GRAPH_LABEL",
        "E_UNKNOWN_BRIDGE",
        "E_AMBIGUOUS_PROFILE",
        "E_UNKNOWN_BINDING",
        "E_BINDING_OUT_OF_SCOPE",
    ],
    conformance_tiers: &[
        CoveQlConformanceTier {
            tier: 0,
            name: "semantic_correctness",
            authority: "materialized_coveql",
            required_surfaces: &[
                "object",
                "association",
                "evidence",
                "projection",
                "temporal",
                "json",
                "arrow",
                "datafusion",
                "explain",
            ],
            required_invariant:
                "valid CoveQL semantics match materialized COVE-O/COVE-MAP readback without relying on optional accelerators",
        },
        CoveQlConformanceTier {
            tier: 1,
            name: "fallback_invariance",
            authority: "materialized_coveql_with_explicit_fallbacks",
            required_surfaces: &[
                "absent_optional_metadata",
                "valid_optional_metadata",
                "stale_optional_metadata",
                "corrupt_optional_metadata",
                "unsupported_optional_metadata",
                "security_blocked_optional_metadata",
            ],
            required_invariant:
                "optional metadata may change plans and diagnostics but not visible rows unless policy requires a structured rejection",
        },
        CoveQlConformanceTier {
            tier: 2,
            name: "acceleration_proof",
            authority: "optimized_output_compared_or_proven_equivalent",
            required_surfaces: &[
                "coded_kernel",
                "index_only",
                "coverage_pruning",
                "execution_code_remap",
                "zero_copy",
                "datafusion_pushdown",
                "manifest_bridges",
            ],
            required_invariant:
                "every optimized, coded, indexed, zero-copy, or pushed-down path proves exact equivalence or compares against materialized output",
        },
    ],
};

pub fn conformance_profile() -> &'static CoveQlConformanceProfile {
    &COVEQL_CONFORMANCE_PROFILE
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ExplainJsonSchema {
    pub version: &'static str,
    pub modes: &'static [&'static str],
    pub required_top_level_fields: &'static [&'static str],
    pub required_operation_context_fields: &'static [&'static str],
    pub required_coded_execution_fields: &'static [&'static str],
    pub required_coded_operator_contract_fields: &'static [&'static str],
    pub required_physical_sidecar_validation_fields: &'static [&'static str],
    pub required_physical_plan_sidecar_fields: &'static [&'static str],
}

pub const EXPLAIN_JSON_SCHEMA: ExplainJsonSchema = ExplainJsonSchema {
    version: EXPLAIN_JSON_SCHEMA_VERSION,
    modes: &["public", "developer", "proof", "coded", "forensic"],
    required_top_level_fields: &[
        "schema_version",
        "mode",
        "coveql_version",
        "core_version",
        "primary_profile",
        "profiles",
        "profile_contracts",
        "root",
        "grain",
        "operation",
        "temporal_mode",
        "canonical_order",
        "visibility_applied",
        "redaction_applied",
        "fingerprints",
        "operation_context",
        "logical_plan",
        "physical_plan",
        "resolved_dependencies",
        "predicate_forms",
        "trusted_metadata",
        "ignored_metadata",
        "fallbacks",
        "rejections",
        "decode_boundaries",
        "residual_predicates",
        "visibility",
        "redactions",
        "warnings",
        "diagnostics",
        "execution",
    ],
    required_operation_context_fields: &[
        "language_version",
        "core_version",
        "grammar_version",
        "resolved_ast_version",
        "logical_plan_version",
        "physical_plan_version",
        "projection_dependency_contract_version",
        "predicate_normal_form_version",
        "explain_json_schema_version",
        "profile_contract_version",
        "bridge_contract_version",
        "operation",
        "file_len",
        "file_id",
        "footer_crc32c",
        "primary_profile",
        "dataset_id",
        "snapshot_id",
        "selected_snapshot_ref",
        "schema_fingerprint",
        "semantic_map_fingerprint",
        "file_digest",
        "authority",
        "dataset",
        "temporal_mode",
        "temporal",
        "branch",
        "tombstone",
        "visibility_applied",
        "redaction_applied",
        "security",
    ],
    required_coded_execution_fields: COVEQL_CONFORMANCE_PROFILE.required_coded_explain_fields,
    required_coded_operator_contract_fields: COVEQL_CONFORMANCE_PROFILE
        .required_coded_operator_contract_fields,
    required_physical_sidecar_validation_fields: COVEQL_CONFORMANCE_PROFILE
        .required_physical_sidecar_validation_fields,
    required_physical_plan_sidecar_fields: COVEQL_CONFORMANCE_PROFILE
        .required_physical_plan_sidecar_fields,
};

pub fn explain_json_schema() -> &'static ExplainJsonSchema {
    &EXPLAIN_JSON_SCHEMA
}
